# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "http://blog.shiv.me/"
title: Reflections
copyright: "Copyright 2007-2024 © Shivanand Velmurugan"
#paginate: 10
pagination.pagerSize: 5
theme: [hugo-PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

# custom properties
footnotereturnlinkcontents: "↩︎︎"


minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    ContentDir: 'content'
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives/
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 15
        #- name: Series
        #  url: series/
        #  weight: 20
        - name: Projects
          url: projects/
          weight: 20
        - name: Home
          url: http://shiv.me

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Reflections - on life, on software, the making of software, and its impact on life"
  author: Shivanand Velmurugan

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "I am Shiva."
    Content: "I write about life, software, and their influence on each other. In 2017, my daughter was born. There was little to say, a lot to live, and
      even more to learn. However, it is now 7 years later. It's 2025: time to write again."
#  Much like the stoics of the past, I aspire to live to these words from [Nirvana Shatakam](https://shlokam.org/nirvanashatakam/).<br>
#  
#  न मे द्वेष रागौ न मे लोभ मोहौ<br>
#  न मे वै मदो नैव मात्सर्य भावः।<br>
#  न धर्मो न चार्थो न कामो न मोक्षः<br>
#  चिदानन्द रूपः शिवोऽहम् शिवोऽहम्।<br>
#  which translates to <br>
#  *Neither do harbor hatred nor passion, no greed or delusion,<br>
#  Neither do I take pride, nor do I pursue jealousy,<br>
#  I not bound by dharma (righteousness), artha (wealth), kama (desire) and moksha (liberation),<br>
#  I am Shiva, the form of consciousness and bliss, <br>
#  I am Shiva (that which is not)*<br><br>
#  

  socialIcons:
    - name: github
      title: View Projects on Github
      url: "https://github.com/shiva"
    - name: X
      title: Find Shiva on X/Twitter
      url: "https://twitter.com/shiva"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://ko-fi.com/shivanand"

  editPost:
    URL: "https://github.com/shiva/blog/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
