baseurl = "http://blog.shiv.me/"
languageCode = 'en-us'

#pagination.pagerSize = 5
canonifyurls = true
DefaultContentLanguage = "en"
#enableInlineShortcodes = true
#theme = "HugoTeX"
#theme = "hugo-bearcub"
#theme = "hugo-blog-awesome"

theme = "hugo-tufte"
#theme = "hugo-ink"
#theme = "hugo-theme-minima"
#theme = "hugo-theme-novela"

copyright = "Copyright 2024"
footnotereturnlinkcontents="↩︎︎"
staticDir = "content/static"



[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[permalinks]
    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/:year/:month/:day/:slug/"

[params]
    goToTop = true

    # switch for turning on/off lights.
    switch = ["🌚", "🌝"]

    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "white"

    # Title. Some themes like This
    title = "shiv.me"
    description = "Reflections"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = ""

    # Footer; Markdown accepted here.
    footer = "Copyright 2016 &copy; Shivanand Velmurugan"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    email = "shiv@shiv.me"
    ganalytics = "UA-5610776-2"
    googleAnalytics = "UA-5610776-2"
    #disqusShortname = "shiva"

    DateForm = "Mon, Jan 2, 2006"

    # Remove, comment, or leave blank any field to leave them out.
    [params.social]
    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
      github = "https://github.com/shiva"
      bitbucket = "https://bitbucket.org/shiva/"
      twitter = "https://twitter.com/shiva"
      stackoverflow = "http://stackoverflow.com/users/11018/shiva"
      linkedin = "https://ca.linkedin.com/in/vshivanand"
      facebook = "https://www.facebook.com/shivanand"

    [params.author]
      name = "Shiva Velmurugan"
      abstract = "I'm a product manager by day, and programmer by night. I am intrigued by abstraction, programming languages and organizing data."

[menu]
    [[menu.main]]
        name = "About"
        url = "http://shiv.me/#about"


[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false

